name: CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  AZURE_FUNCTIONAPP_NAME: valyria-batch-vepdataloader
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'build'
  DOTNET_VERSION: '3.1.301'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

  deploy-function:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Publish Function
      run: dotnet publish src/Functions/Functions.csproj --configuration Release --output build
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
